language: python
python:
- 2.7
- 3.5
- 3.6
script: make test
deploy:
  matrix:
  - provider: pypi
    user: mirucha
    password:
      secure: p971DB8HxHvIEfSg5l3UjicCxAmBqFV0tnj8Em8FRIGvOZEHgbCuLpSNSWdr5X8KFpLq+5W0uUJhzLj6lTQFXZXfqclDq8SLT7CdJCT62xjM5NvIWV0znS3A6TBBJsY/rTpEnxK3PuFbyn4WLRE624IG8xe8J2M8AYMlRrs4RFRh3DNA/mbgd6pi7uV/cYFu6OLp0Asu0bSV1BqU3aJFX//FJ3RYjknwCyV8JAly1eiDTgYprNP13oCDsNFkBa6Dn0BaPn
        /vYZei7D/ismooLxdlLY0NUAjbpqppj6Fuyb+/aBa2Dp7udxReS4/9rX0fIXl7q+qqMdkp5N6+W9jILa4Ykr0a37348IDx2GpD1+PdYzZTdC1m7JqKfAZ/YV+f7RNuZoUQz1fumx7993QYk2n4ONUkTIFbjakzZf9Ylh0ISo7ym461RHl/mIJh94DvFifkqkNVgWeBX1wyS1UCa+wqTnYEg50Mdgvhj0ZcQxKv5ZMUh6fiK3bS/fBO084Lkyd0dggEdjB42tqCd4s0sL2SI
        5/2M5D+yYqq6NZX15i/GjpQmeee/Gwv5YWHB/GOA8+jFEpGa8Em630b8jpoxN/o5GYJTAoVcqe3mvEjXeb0Ga7Oeo1TNlrcBYsZHrN/mL4aS+c3XSm4HATKdY1vsntP5R9hevtHObXRjTjcXik=
    on:
      tags: true
      branch: master
  password:
    secure: QoB9VtpJiqQ6DbQnAHSX76cPc9eVTOyDkVqNgicJbc15ykG23TX6U+aW0GYIklPOtmP6ptPKqi8vOyeabaLwddF7ZkKcijGM+SfXOQUwwCdw9eYEJP2YBt6UuBvoLYRIXZRgv2HPbqTy7GXP0qRtmyazzoDM11uwQ37Jmi2by16ZZ30U9kfsfeDfjTna/g/3204MW9oc/I4bR1nlagByCZD3DKxjhaEuOmJMe2jjxhhb9qHTd/yIg3rHlhL8fxn02VqKuhI5Ar9YXYYufbgj8IDv5168CFh307Pxv2LPnAbOUtcEwIpj3ykO8Y+MEdVb7wBr16NYwx3FE3Y9D7QVr2lqKaaDGdFRSvtBurjT2u23lbLj85S73A0fPr7O3yuHR0kQ1oYuv/sGlgsev2ckK/t9gvb8Y15qbqyRLKEEJ7HkGtAnlkhkQWnRTnktTj54Q1Sq382Dmuk0dEPIldurkunBxWqLptZyPABN4GeZs2JtzRl7XDumPgG/eKNoHdVeqSwnpM3Ne+OZnP40n+0D893DX++HBuSxMTasjIcmk4Mbs8YPKEvJkii2JzdEd/Qoubypiib+x0AATYwO1ZJqnyt+2RwjwI2QGx3IqYNIWT9Vd03zUMs0QbiOhfhPfYf1HZBN241niEuYyXTiYxxjsYy5BdOiHU/omoL+Zu8MYng=
